### ISSUE TITLE
Version resolved was version in versions.props, not version from versions.lock

### ISSUE THREAD

**Issue by gregakinman** [palantir/gradle-consistent-versions#31]
cc @pkoenig10 

## What happened?

A repository declares version 1.1 of a dependency (let's say dependency `foo`) in versions.props. One of its dependencies (dependency `bar`) declared in versions.props transitively depends on version 1.2 of `foo`. (Let's say `bar` depends on `foo` 1.2 since `foo` 1.2 adds a feature that `bar` uses). When `.gradlew --write-locks` is run, versions.lock locks version 1.2 for `foo`.

One of the subprojects does not depend on `bar` in any of its configurations. It does, however, depend on `foo` in one of its configurations. The version of `foo` that ends up getting resolved in this configuration is 1.1.

So, versions.props says 1.1, versions.lock says 1.2, and the actual version that gets resolved in a configuration is 1.1.

(Sorry if the example is difficult to follow - it's a genericization of a real situation that happened on an internal repo. I can point you to that internal repo if you'd like).

## What did you want to happen?

I expected the resolved version of `foo` to be 1.2. I expected this because I thought versions.lock would be the record of what every version would be resolved to globally. However, this wasn't the case - the version in versions.props got picked. Is this behavior expected?

**Comment by topherinternational** [comment]
Pretty sure I saw the same thing in another repo. Expected behavior for me would be that some resolution-type task fails showing me my versions.lock and versions.props are out of sync, or at worst, silently uses the locked version and not the props version.

**Comment by dansanduleac** [comment]
I think what you're hitting here is the fact that we only _lock_ the java configurations that gradle uses at compilation/runtime (`runtimeClasspath`, `compileClasspath`), whereas other configurations don't get the versions from `versions.lock` enforced on them.

However, all configurations (though you can exclude some via the extension) get the constraints from `versions.props`. This is because `versions.props` is like a one-way function, providing
1. version injection (so you don't have to specify it inline)
2. version grouping (lines containing `*`)

so we're comfortable using it to inject versions into whatever configuration.

On the other hand, `versions.lock` is like a two-way function: it not only applies constraints onto some configurations, but it also updates its own versions from those configurations (across all projects). This makes it harder to reason about, as it's easy to accidentally group together versions from configurations that have different use cases.

A specific reason why we don't lock all configurations is that a lot of plugins rely on their own configurations to wire up whatever binaries/compilers they need (`scala` as a prime example), and they might need entirely different versions than what your java projects use.

**Comment by dansanduleac** [comment]
@christopherpanderson we should add better docs around the expected behaviour then.

In reality, `versions.props` is not supposed to be in sync with `versions.lock` (the "syncing" only goes one way).
It only defines some constraints of the form "I need at least this version". Then, the lock file decides what version satisfies those constraints along with the constraints coming from transitives in all of your projects.

If we made `versions.props` apply strict constraints (I get exactly what I asked for, or fail), then you'd have to potentially change a bunch of lines any time you upgrade a module that has lots of other dependencies. Instead of forcing users to upgrade their `versions.props` manually in this way, we provide an entirely automatable process, via writing locks, the result of which is then reviewable by  observing if the locks have changed in a PR.

Specifically, any project should rely _only_ on `versions.lock` to be the source of truth of "what versions will I be using in production".

**Comment by dansanduleac** [comment]
I should also mention that while this is how we interpret `versions.props`, gradle also has primitives that allow you to declare a _strictly_ constraint on a certain version, causing the build to fail if the constraint wasn't met:
https://docs.gradle.org/current/userguide/declaring_dependencies.html#sub:declaring_dependency_rich_version

e.g. in a project using consistent versions, you could do
```gradle
allprojects {
	dependencies {
	    constraints {
		    rootConfiguration 'org.slf4j:slf4j-api', {
		        version { strictly '[1.7, 1.8[' }
		    }
		}
	}
}
```

**Comment by dansanduleac** [comment]
More clearly explained how this works in #96.
Please see https://github.com/palantir/gradle-consistent-versions#versionsprops-lower-bounds-for-dependencies

> Note that this does not force okhttp to exactly 3.12.0, it just declares that your project requires at least 3.12.0. If something else in your transitive graph needs a newer version, Gradle will happily select this. See below for how to downgrade something if you really know what you're doing.
