### ISSUE TITLE
Strange Multiple BOM Behavior

### ISSUE THREAD

**Issue by tpetracca** [palantir/gradle-consistent-versions#65]
## What happened?

I've been trying [unsuccessfully] to figure out a way to cleanly apply two BOMs to a repository that have some overlapping recommendations (at different versions). Here's an interesting observation:

If you apply bom1 to all projects but X and the bom2 only to project X:
- any dependencies in project X that have version recommendations in bom1 but not bom2 end up not having a version recommended for that dep in that project. This was behavior I expected; it tells me that bom1 wasn't applied to the project, because well, it wasn't.
- any dependencies in project X that have version recommendations in bom1 *and* bom2 end up treating both boms as constraints. So if bom1 has a higher version for one of said dependencies, than the project will recommend/use that version and not bom2's. This was unexpected; I didn't apply bom1 to this project, why is it being used as a constraint? Also under this logic I would have expected my first bullet point to have also used bom1's constraint and give a recommendation. 

## What did you want to happen?

Ideally I would have a way to apply boms to only certain projects. I have a repository that contains two projects/services with wildly different classpath/dependency/version requirements. I would love be able to give them different boms and have those boms (and only those boms) applied where I apply them.

**Comment by dansanduleac** [comment]
This is intentional. Consistent versions has made the explicit choice to produce a single unified list of versions for _all_ projects, which then gets applied as constraints via the lock file.

For any BOM applied to any project, its recommendations will make their way onto the "consistent" unified configuration, so that's why the constraints from both BOMs are applied when deciding the lockfile. The versions from the lock file then get enforced onto all projects.

What you're asking for is not technically impossible, but would require a different lock file for each group of projects that have wildly different classpaths, and I'm not sure we want to build such functionality, because it comes with a pretty high complexity cost.

Would it be possible to split your build into two projects, both of which can adhere to a single master set of consistent versions?

**Comment by dansanduleac** [comment]
Added some wording in #96 to pre-empt this kind of question in the future:
https://github.com/palantir/gradle-consistent-versions#boms
> Make sure you apply BOMs within an allprojects closure, as gradle-consistent-versions must be able to unify constraints from all subprojects.
